apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus-operator
    role: alert-rules
    release: prometheus-operator
  name: interactions-app-alert-rules
spec:
  groups:
    - name: interactions-app-alerts
      interval: 1m
      rules:
        # Azure Service Bus Alerts
        - alert: NoASBMessagesProcessedDuringBusinessHours
          expr: (sum by(cluster, namespace, platz_stamp) (increase(st_contactcenter_asb_process_message_total{metadata_component="contactcenter-interactions-service"}[10m])) == 0) AND on() (hour() >= 13 OR hour() == 0)
          for: 1m
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: "No Azure Service Bus messages processed in the last 10 minutes between 9am to 8pm EST"
            description: 'No Azure Service Bus messages processed in the last 10 minutes between 9am to 8pm EST in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: NoASBMessagesProcessedOutsideBusinessHours
          expr: (sum by(cluster, namespace, platz_stamp) (increase(st_contactcenter_asb_process_message_total{metadata_component="contactcenter-interactions-service"}[90m])) == 0) AND on() (hour() >= 1 AND hour() <= 12)
          for: 5m
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: "No Azure Service Bus messages processed in the last 90 minutes between 8pm to 9am EST"
            description: 'No Azure Service Bus messages processed in the last 90 minutes between 8pm to 9am EST in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: ASBMessageProcessingDurationHigh
          expr: (max without() (sum(rate(st_contactcenter_asb_process_message_duration_sum{container="contactcenter-interactions-service"}[1m])) by (handler_name, cluster, namespace, platz_stamp) / sum(rate(st_contactcenter_asb_process_message_duration_count{container="contactcenter-interactions-service"}[1m])) by (handler_name, cluster, namespace, platz_stamp)) / 1000) >= 20
          for: 5m
          labels:
            severity: warning
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} {{ "{{$labels.handler_name}}" }} Azure Service Bus message process duration > 20 seconds over the last 5 minutes'
            description: 'Azure Service Bus {{ "{{$labels.handler_name}}" }} message process duration > 20 seconds in the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: ASBMessageDeadLettered
          expr: sum by(cluster, namespace, platz_stamp) (st_contactcenter_asb_process_message_failed_total{container="contactcenter-interactions-service"}) - (sum by(cluster, namespace, platz_stamp) (st_contactcenter_asb_process_message_failed_total{container="contactcenter-interactions-service"} offset 5m)) >= 1
          for: 0s
          labels:
            severity: warning
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} {{ "{{$labels.handler_name}}" }} Azure Service Bus message dead lettered'
            description: 'Azure Service Bus {{ "{{$labels.handler_name}}" }} message process dead lettered in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: ASBMessageProcessingErrorsHigh
          expr: sum by(cluster, namespace, platz_stamp) (rate(st_contactcenter_asb_process_message_delayed_total{container="contactcenter-interactions-service"}[1m])) + sum by(cluster, namespace, platz_stamp) (rate(st_contactcenter_asb_process_message_failed_total{container="contactcenter-interactions-service"}[1m])) > 0.5
          for: 5m
          labels:
            severity: warning
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} {{ "{{$labels.handler_name}}" }} Azure Service Bus message processing errors high in the last 5 minutes'
            description: 'Azure Service Bus {{ "{{$labels.handler_name}}" }} message processing errors high in the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        # API Alerts
        - alert: APIResponseTimeHigh
          expr: (sum(rate(st_request_duration_seconds_sum{metadata_component="contactcenter-interactions-service", action!=""}[1m])) by (cluster, namespace, platz_stamp, action, code) / sum(rate(st_request_duration_seconds_count{metadata_component="contactcenter-interactions-service", action!=""}[1m])) by (cluster, namespace, platz_stamp, action, code)) >= 1
          for: 5m
          labels:
            severity: warning
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} {{ "{{$labels.action}}" }} API response time > 1 second in the last 5 minutes'
            description: 'API {{ "{{$labels.action}}" }} response time > 1 second in the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: APIResponseTimeCritical
          expr: (sum(rate(st_request_duration_seconds_sum{metadata_component="contactcenter-interactions-service", action!=""}[1m])) by (cluster, namespace, platz_stamp, action, code) / sum(rate(st_request_duration_seconds_count{metadata_component="contactcenter-interactions-service", action!=""}[1m])) by (cluster, namespace, platz_stamp, action, code)) >= 20
          for: 5m
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} {{ "{{$labels.code}}" }} {{ "{{$labels.action}}" }} API response time > 20 seconds in the last 5 minutes'
            description: '{{ "{{$labels.code}}" }} {{ "{{$labels.action}}" }} API response time > 20 seconds in the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: 5XXErrorRateCritical
          expr: sum(rate(st_request_duration_seconds_count{metadata_component="contactcenter-interactions-service", action!="",code=~"5.."}[1m])) by (cluster, namespace, platz_stamp, action, code) > 0
          for: 5m
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} 5XX errors for the last 5 minutes'
            description: '5XX errors for the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: 4XXErrorRateHigh
          expr: sum(rate(st_request_duration_seconds_count{metadata_component="contactcenter-interactions-service", action!="",code=~"4(0[025678]|[1-9][0-9])"}[1m])) by (cluster, namespace, platz_stamp, action, code) > 0
          for: 5m
          labels:
            severity: warning
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} 4XX errors for the last 5 minutes (excluding 401, 403, 404)'
            description: '4XX errors for the last 5 minutes in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        # Kafka Alerts
        - alert: KafkaConsumptionErrors
          expr: sum without() (st_PubSub_Kafka_Consumer_Pipeline_Error{container="contactcenter-interactions-service"}) > 0
          for: 0s
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: '{{ "{{$value | humanize}}" }} Kafka consumption errors'
            description: 'Kafka consumption errors in {{ "{{$labels.platz_stamp}}" }}'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ

        - alert: KafkaProducerErrors
          expr: (rate(st_PubSub_Kafka_Producer_Error{metadata_component="contactcenter-interactions-service"}[1m])) > 0
          for: 1m
          labels:
            severity: critical
            team: contactcenter
          annotations:
            summary: '{{ "{{$value}}" }} rate of Kafka Producer Errors in last 1m'
            description: 'Kafka Producer Errors > 0 in past minute'
            runbook_url: https://servicetitan.atlassian.net/wiki/x/CYHruQ