name: "Build and Push: Release"
on:
  push:
    tags:
      - "*v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-hotfix.[0-9]+"
  workflow_dispatch:

jobs:
  approve-stage:
    name: Approve Stage Deployment
    runs-on: ubuntu-22.04
    environment: Stage Approval
    concurrency:
      group: prod-approval
      cancel-in-progress: true
    steps:
      - name: Deployment Approved
        run: echo "Approved"
  deploy-stage:
    needs: approve-stage
    uses: ./.github/workflows/deploy-reusable.yml
    secrets: inherit
    with:
      environment: stage
      stamps: "['wus2-01', 'eus2-01']"
  approve-prod:
    name: Approve Prod Deployment
    needs: deploy-stage
    runs-on: ubuntu-22.04
    environment: Production Approval
    concurrency:
      group: prod-approval
      cancel-in-progress: true
    steps:
      - name: Deployment Approved
        run: echo "Approved"
  deploy-prod:
    needs: approve-prod
    uses: ./.github/workflows/deploy-reusable.yml
    secrets: inherit
    with:
      environment: prod
      stamps: "['wus2-01', 'eus2-01']"
