name: "Build and Push: QA"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-reusable.yml
    secrets: inherit
    with:
      environment: qa
      stamps: "['wus2-01', 'wus2-02']"

  performance-smoke-test:
    needs: deploy
    uses: ./.github/workflows/k6-reusable.yml
    secrets: inherit
    with:
      environment: qa
      workload: smoke
      path: .performance/src/tests/*.ts
